### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by emawbgit** [haghish/githubtools#1]
Hi, I am running the installer for githubtools from stata (I've given it full permissions and I'm running stata as administrator). Yet, I receive this:
![image](https://user-images.githubusercontent.com/65594313/226839287-33103501-eb8b-4d69-a423-b905dc0b7fe4.png)

Any hint? Thanks

**Comment by haghish** [comment]
it could be that your working directory is not allowing installation, a common problem in MS Windows. You were in "Documents", perhaps it'd have been better to start a new directory for the operation.
